# Generated by Django 5.1.4 on 2025-01-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_is_approved_comment_parent_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='highlight_summary',
            field=models.TextField(blank=True, null=True, verbose_name='Resumo de Destaque'),
        ),
        migrations.AddField(
            model_name='post',
            name='list_summary',
            field=models.TextField(blank=True, null=True, verbose_name='Resumo da Lista'),
        ),
    ]
