# Generated by Django 5.1.4 on 2025-01-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_canonical_url_post_keywords_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Descrição para SEO, até 160 caracteres.', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_robots',
            field=models.CharField(choices=[('index, follow', 'Index, Follow'), ('noindex, nofollow', 'No Index, No Follow'), ('noindex, follow', 'No Index, Follow'), ('index, nofollow', 'Index, No Follow')], default='index, follow', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Título para SEO, até 60 caracteres.', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='og_description',
            field=models.TextField(blank=True, help_text='Descrição para Open Graph.', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Imagem para Open Graph.', null=True, upload_to='og_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='og_title',
            field=models.CharField(blank=True, help_text='Título para Open Graph.', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='Dados estruturados em JSON-LD.', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='twitter_description',
            field=models.TextField(blank=True, help_text='Descrição para Twitter Cards.', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='twitter_image',
            field=models.ImageField(blank=True, help_text='Imagem para Twitter Cards.', null=True, upload_to='twitter_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='twitter_title',
            field=models.CharField(blank=True, help_text='Título para Twitter Cards.', max_length=60, null=True),
        ),
    ]
