# Generated by Django 5.1.4 on 2025-01-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_meta_description_post_meta_robots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_author',
            field=models.CharField(blank=True, help_text='Autor para SEO.', max_length=100, null=True),
        ),
    ]
